name: Robot Framework 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ==============================
      # SYSTEM DEPENDENCIES (FIX UBUNTU 24.04)
      # ==============================
      - name: Install system dependencies
        run: |
<<<<<<< HEAD
    sudo apt-get update
    sudo apt-get install -y wget unzip
    sudo apt-get install -y libnss3 libxi6 libgbm-dev
    sudo apt-get install -y libasound2t64
=======
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y libnss3 libxi6 libgbm-dev libasound2t64
>>>>>>> 9db10d0 (Update CI workflow)

      # ==============================
      # INSTALL GOOGLE CHROME
      # ==============================
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Verify Chrome version
        run: google-chrome --version

      # ==============================
      # RUN TESTS
      # ==============================
      - name: Run Robot Framework tests
        run: robot -d results tests/

      # ==============================
      # UPLOAD REPORTS
      # ==============================
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
